### ISSUE TITLE
Swap Proposal Introduces Massive MEVil Potential

### ISSUE THREAD

**Issue by TheBlueMatt** [brc20-devs/brc20-proposals#2]
I was recently pointed to your swap proposal using liquidity pools described at https://github.com/brc20-devs/brc20-proposals/blob/main/bp02-module-swap/spec.md and am incredibly worried about the negative implications it would have for mining centralization and Bitcoin mining incentives. Specifically, as we saw happen in Ethereum, the deployment of Uniswap-like liquidity pools can cause a massive pressure on block template centralization and totally wreck any semblance of decentralization of the underlying cryptocurrency. While PoW and PoS systems are somewhat different in regards to MEV (I wrote a long-form post on the differences and what Bitcoin cares about specifically at at https://bluematt.bitcoin.ninja/2024/04/16/stop-calling-it-mev/), the underlying result of a naive Uniswap-style liquidity pool is the same (and in fact much worse on PoW) - block template selection becomes fully centralized and controlled by one or three large companies and the underlying cryptocurrency's long-term value is wrecked.

Luckily, there are several things that can be done to avoid these kinds of issues:
 * Swap-based markets has a good bit lower MEVil potential over liquidity pool-based markets. Online market makers can operate as if they were a part of a liquidity pool in a swap-based marketplace, so building online market making software could create a similar result for users without as much MEVil potential.
 * Executing swap contract trades in a randomized order across a random subset of blocks largely removes most MEVil games miners can play - by restricting miners from knowing exactly how a trade will clear until after the block has been mined they can't as easily know how to construct templates which arb DEXes directly.

I tried reaching out to domodata on Twitter a while back and never heard back, sadly, so am opening this in the hopes we can start a useful dialog here.

**Comment by jiedo** [comment]
Thank you for your suggestion.
In fact, due to the participation of the sequencer role, miners cannot intervene in the brc20-swap process by reordering transactions. In addition, due to the user's chain signature, the best strategy for the sequencer is to always keep all transaction data unchanged. In this case, malicious clamping problems similar to Uniswap will hardly occur.

**Comment by TheBlueMatt** [comment]
Thanks for your input. It wasn't quite obvious to me whether any of the operations were doable without the sequencer or if there's competition between sequencers (eg imagine a miner becomes a sequencer, they could almost certainly make more money than a naive sequencer by arb'ing at the time of block construction). Are users tied to one sequencer for a given pool or can they pick one?

**Comment by samedcildir** [comment]
There are some operations that can be submitted without a sequencer, but these operations only affect the wallet that initiated the operation, so there is no competition between wallets for these operations. All liquidity add/remove and swap operations are only performed by the sequencer.

Users are tied to a single sequencer per pool, so there is no sequencer competition as well.

**Comment by jiedo** [comment]
> Thanks for your input. It wasn't quite obvious to me whether any of the operations were doable without the sequencer or if there's competition between sequencers (eg imagine a miner becomes a sequencer, they could almost certainly make more money than a naive sequencer by arb'ing at the time of block construction). Are users tied to one sequencer for a given pool or can they pick one?

Sorry for not replying to you in time,

A module instance can only have 1 sequencer, which is specified at the time of deployment. The new sequencer must obtain user deposits again, which is difficult. This requires the sequencer to maintain credibility.

For sequencers that have already maintained a large pool, because each user's signature includes all his previous behaviors, it is difficult for the sequencer to cherrypick transactions. The easiest way is to keep the transaction unchanged and not manipulate it
